package org.omancode.r;

/**
 * Exception generated by R interface code.
 * 
 * @author Oliver Mannion
 * @version $Revision$
 */
public class RInterfaceException extends Exception {

	/**
	 * Serialization ID.
	 */
	private static final long serialVersionUID = -2048430471489617308L;

	public RInterfaceException(String message, Throwable cause) {
		super(message, cause);
	}

	public RInterfaceException(String message) {
		super(message);
	}

	public RInterfaceException(Throwable cause) {
		super(cause);
	}

}
