.pep <- function(expr) {
	## Parse then evaluate a character vector (expr), returning AND printing the
	## result if the result is visible (ie: the REP parts of the REPL).
	## Modelled on the source() function.
	## Syntax errors will be produced by the parse function.
	## Evaluation errors will be produced by the eval.with.vis function.
	## Warnings are explicitly trapped and printed, because JRI doesn't
	## output them to the console when options(warn = 0) for expressions 
	## evaluated via calls to parseAndEval. 
	## Errors are not suppressed by JRI and output straight to the console.
	## NB: warnings are printed at the end of the evaluation of all lines
	## in the expr, as opposed to after each line as it's executed.
	## NB: because warnings are muffled, last.warning won't contain any
	## warnings generated by expr
	## NB: traceback() won't work on commands executed this way

	localWarnings <- list()
	
	#wrap in try so if it errors this function will continue to execute 
	#and print any warnings
	result <- try(withCallingHandlers(
		.Internal(eval.with.vis(parse(text=expr), .GlobalEnv, baseenv())),
		
			## trap and record warning in localWarnings list
			warning = function(w) {
				## because w$call can be NULL, we must wrap in list()
				## as per R FAQ 7.1
				localWarnings[length(localWarnings)+1] <<- list(w$call)
				names(localWarnings)[length(localWarnings)] <<- w$message
				
 				## don't print warning to console
				invokeRestart("muffleWarning")  
			}
			))
			
	if (!is(result,"try-error") && result$visible) {
		## print result if visible
		show(result$value)
	}
	
	if (length(localWarnings) > 0) {
		## explicitly print warnings if they exist
		show(structure(localWarnings, class = "warnings"))
	}
	
	## return value
	if (!is(result,"try-error")) {
		result$value
	}
}

lsNoFunc <- function (...) {
	#eg: lsNoFunc(all.names=TRUE)
	#displays objects as per ls() except for those that are functions
	#eg: rm(list = lsNoFunc(all.names=TRUE))
	#removes all objects (except functions)
	objs <- ls(".GlobalEnv", ...)
	klass <- sapply(objs, function(X) { class(get(X)) })
	klass <- .filter(klass, include = "all", exclude = "function")
	names(klass)
}

.getObjects <- function (include = "all", exclude = "function") 
{
	#.getObjects() #show all except functions
	#.getObjects(exclude="") #show all including functions
	#.getObjects(c("data.frame","numeric") #show only dataframes and numeric vec
	#get a list of all the objects in the 
	#global environment, their class and their info
	#if showFunctions == TRUE returns functions as well
	objs <- ls(".GlobalEnv")
	klass <- sapply(objs, function(X) { class(get(X)) })
	klass <- .filter(klass, include, exclude)
	
	result <- NULL
	result$names <- names(klass)
	result$class <- klass
	result$info <- sapply(result$names, function(X) { .getInfo(get(X)) })
	
	names(result$class) <- NULL
	names(result$info) <- NULL
    result
}

.filter <- function (vec, include = "all", exclude = "function") {
	#.filter(c("a","b","c"), c("c","a"))
	vec[.filteredIndices(vec,include,exclude)]
}

.filteredIndices <- function (vec, include = "all", exclude = "function") {
	#.filteredIndices(c("a","b","c"), c("c","a"))
	if (any(include != "all")) {
		vec %in% include
	} else {
		!vec %in% exclude
	}
}

.getParts <- function (o, include = "all", exclude = "function") 
{
	#.getParts(o)
	#.getParts(o, "integer")
	#.getParts(o, "logical")
	#.getParts(c(1,2,3))
	#get a list containing the names, class, and info
	#about the parts of an object
	#if the object has no parts (or all parts are filtered out), returns NULL
    result <- NULL
    
    if (class(o) == "matrix" || (class(o) == "table" && length(dim(o)) == 2)) {
    	#matrix (ie: 2d array) and 2d tables
    	klass <- apply(o, 2, class)

        if (is.null(names(klass))) {
        	#unnamed, so give it some names
        	names(klass) <- .getPartNames(o[1,])
    	}

    	#just test first class because the rest will be the same
    	#since this is a matrix/table
    	if(.filteredIndices(klass[1], include, exclude)) {
			result$names <- names(klass)
			result$class <- klass
			result$info <- apply(o, 2, .getInfo)
		}
    	
    } else if (mode(o) == "list") {
    	#lists and dataframes
    	
        klass <- sapply(o, class)
        
        if (is.null(names(klass))) {
        	#unnamed, so give it some names
        	names(klass) <- .getPartNames(o)
    	}
    	
    	#filter out elements based on class
		selection <- .filteredIndices(klass, include, exclude)
		ofiltered <- o[selection]
		klassf <- klass[selection]
		
		#if we have any elements
		if (length(ofiltered) > 1) {
			result$names <- names(klassf)
			result$class <- klassf
	
			result$info <- sapply(ofiltered, .getInfo)
		}
    }

	names(result$class) <- NULL
	names(result$info) <- NULL
    result
}

.getPartNames <- function (o) {
	#.getPartNames(children)
	#.getPartNames(children$accom)
	#.getPartNames(array(c(1),c(2,2))[1,])
	resultNames <- c()
	#if o has no names, then use number index as a name
	if (!is.null(o) && is.null(names(o))) {
		if (mode(o) == "list") {
			#lists and dataframes
			resultNames <- paste("[[", c(1:length(o)), "]]", sep="")
		} else {
			#matrix (ie: 2d array) and 2d tables
			resultNames <- paste("[,", c(1:length(o)), "]", sep="")
		}
	}  else {
		resultNames <- names(o)
	}
	resultNames
}

.getInfo <- function (o) {
	#.getInfo(obj)
	#returns information about an object, or empty chr ""
	#if there is no information
	result <- c("")

	if (class(o) == "data.frame") {
		result  <- paste(class(o), " ", dim(o)[1], " obs. ", dim(o)[2], " vars", sep="")
	} else if (class(o) == "matrix") {
		result <- paste(class(o), " ", dim(o)[1], " x ", dim(o)[2], sep="")
	} else if (class(o) == "table") {
		if (length(dim(o)) == 2)
			result <- paste(class(o), " ", dim(o)[1], " x ", dim(o)[2], sep="")
		else if (length(dim(o)) == 1)
			result <- paste(class(o), " 1 x ", dim(o), sep="")
		else
			result <- paste(class(o), " ",length(o), sep="")
	} else if (class(o) == "list") {
		result <- paste(class(o), " ",length(o), sep="")
	} else if (class(o) == "function") {
		result <- class(o)
	} else {
		result <- paste(class(o), " ",length(o), sep="")
	}
	
	result
}